-- products base (no pisa tablas existentes)
CREATE TABLE IF NOT EXISTS products (
  id   INTEGER NOT NULL,
  sku  TEXT,
  name TEXT NOT NULL
);

-- Asegurar IDENTITY en id (o secuencia fallback)
DO $$
BEGIN
  BEGIN
    IF NOT EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_name='products' AND column_name='id' AND is_identity='YES'
    ) THEN
      EXECUTE 'ALTER TABLE products ALTER COLUMN id DROP DEFAULT';
      EXECUTE 'ALTER TABLE products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY';
    END IF;
  EXCEPTION WHEN others THEN
    IF NOT EXISTS (
      SELECT 1 FROM pg_class WHERE relkind='S' AND relname='products_id_seq'
    ) THEN
      EXECUTE 'CREATE SEQUENCE products_id_seq';
    END IF;
    EXECUTE 'ALTER TABLE products ALTER COLUMN id SET DEFAULT nextval(''products_id_seq'')';
  END;
END$$;

-- Primary key si falta
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'products'::regclass AND contype = 'p'
  ) THEN
    ALTER TABLE products ADD CONSTRAINT products_pkey PRIMARY KEY (id);
  END IF;
END$$;

-- Columnas faltantes (seguras / idempotentes)
ALTER TABLE products ADD COLUMN IF NOT EXISTS brand        TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS model        TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS category     TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS subcategory  TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS tags         TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS stock        INTEGER DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS min_stock    INTEGER DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS price        NUMERIC;
ALTER TABLE products ADD COLUMN IF NOT EXISTS price_min    NUMERIC;
ALTER TABLE products ADD COLUMN IF NOT EXISTS price_may    NUMERIC;
ALTER TABLE products ADD COLUMN IF NOT EXISTS image_url    TEXT;

-- Unicidad por sku si falta
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_indexes WHERE indexname = 'products_sku_unique_idx'
  ) THEN
    CREATE UNIQUE INDEX products_sku_unique_idx ON products (sku);
  END IF;
END$$;
